### ISSUE TITLE
Algorithme de génération

### ISSUE THREAD

**Issue by richerarc** [richerarc/Projet-SIM#18]

**Comment by stuntfarmboy** [comment]
Algorithme pour définir le ratio connecteurs / salles :

```
Ratio = ((rand() % (16)) + 25) / 100.f;
```

**Comment by stuntfarmboy** [comment]
@richerarc Revois la fonction obtIndiceAleatoire(), car tu l'a changé vite hier pis de mémoire il n'y avait plus rien d'aléatoire
