### ISSUE TITLE
Contenu

### ISSUE THREAD

**Issue by richerarc** [richerarc/Projet-SIM#4]
Coder la classe correspondant aux portes

**Comment by stuntfarmboy** [comment]
Dom, raccourcit des accesseurs pis commence tes methode en minuscule
obtenir -> obt
defenir -> def

**Comment by DomFC** [comment]
C'est fait, à noter que j'ai pas fait pas fait les accesseurs pour le modèle d'un contenu parce qu'on a pas encore le code pour.
